name: Publish Env1 Packages

on:
  push:
    branches: [ "env1" ]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: env1
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Inject GitHub Token into nuget.config
        run: |
          sed -i "s/%GITHUB_TOKEN%/${{ secrets.LIB_ENV1 }}/g" nuget.config

      - name: Restore
        run: dotnet restore --configfile nuget.config

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack Biology (env1)
        run: dotnet pack ./BiologyLibrary/BiologyLibrary.csproj -c Release -o ./output -p:PackageId=BiologyLibrary.env1 -p:PackageVersion=1.0.0-env1.${{ github.run_number }}

      - name: Pack Chemistry (env1)
        run: dotnet pack ./ChemistryLibrary/ChemistryLibrary.csproj -c Release -o ./output -p:PackageId=ChemistryLibrary.env1 -p:PackageVersion=1.0.0-env1.${{ github.run_number }}

      - name: Pack Physics (env1)
        run: dotnet pack ./PhysicsLibrary/PhysicsLibrary.csproj -c Release -o ./output -p:PackageId=PhysicsLibrary.env1 -p:PackageVersion=1.0.0-env1.${{ github.run_number }}

      - name: Pack Science (env1)
        run: dotnet pack ./ScienceLibrary/ScienceLibrary.csproj -c Release -o  ./output -p:PackageId=ScienceLibrary.env1 -p:PackageVersion=1.0.0-env1.${{ github.run_number }}

      - name: Publish packages to GitHub Packages
        run: dotnet nuget push "./output/*.nupkg" -k "${{ secrets.LIB_ENV1 }}" -s "https://nuget.pkg.github.com/01Prathamesh-dev/index.json" --skip-duplicate




